config/routes.rb
Buurtsms::Application.routes.draw do

  resources :in_messages do
    collection do
      get :getmessage
    end
    member do
      put :mark_as_posted
    end
  end

  resources :out_messages

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'home#index'

end

app/models/in_message.rb
class InMessage < ActiveRecord::Base
  STATUSES = %w"received replied"

  attr_accessible :concat, :concat_part, :concat_ref, :concat_total, :message_id, :message_timestamp, :msisdn, :network_code, :status, :message_text, :to, :message_type, :posted_to_fb
end

app/controllers/in_messages_controller.rb
class InMessagesController < ApplicationController
  before_filter :authenticate_user!, :except => [:getmessage]
  load_and_authorize_resource :except => [:getmessage]

  # GET /in_messages
  # GET /in_messages.json
  def index
    @in_messages = InMessage.order('message_timestamp desc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @in_messages }
    end
  end

  # GET /in_messages/1
  # GET /in_messages/1.json
  def show
    @in_message = InMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @in_message }
    end
  end

  # GET /in_messages/new
  # GET /in_messages/new.json
  def new
    @in_message = InMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @in_message }
    end
  end

  # GET /in_messages/1/edit
  def edit
    @in_message = InMessage.find(params[:id])
  end

  # POST /in_messages
  # POST /in_messages.json
  def create
    @in_message = InMessage.new(params[:in_message])

    respond_to do |format|
      if @in_message.save
        format.html { redirect_to @in_message, notice: 'In message was successfully created.' }
        format.json { render json: @in_message, status: :created, location: @in_message }
      else
        format.html { render action: "new" }
        format.json { render json: @in_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /in_messages/1
  # PUT /in_messages/1.json
  def update
    @in_message = InMessage.find(params[:id])

    respond_to do |format|
      if @in_message.update_attributes(params[:in_message])
        format.html { redirect_to @in_message, notice: 'In message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @in_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /in_messages/1
  # DELETE /in_messages/1.json
  def destroy
    @in_message = InMessage.find(params[:id])
    @in_message.destroy

    respond_to do |format|
      format.html { redirect_to in_messages_url }
      format.json { head :no_content }
    end
  end


  def mark_as_posted
    @in_message = InMessage.find(params[:id])
    @in_message.posted_to_fb = params[:posted]

    respond_to do |format|
      if @in_message.save
        format.html { redirect_to :action => :index, notice: 'Updated' }
        format.json { head :no_content }
      else
        format.html { redirect_to :action => :index, notice: "Unable to save" }
        format.json { render json: @in_message.errors, status: :unprocessable_entity }
      end
    end
  end

  def getmessage #TO BE USED ONLY BY NEXMO API

    # here you can extract more values from parameters as described in nexmo docs.

    text_from_phone_no = params[:msisdn]
    text_body = params[:text]
    text_type = params[:type]
    text_to = params[:to]
    text_network = params[:'network-code']
    text_message_id = params[:messageId]
    text_concat = params[:concat]
    text_concat_ref = params[:'concat-ref']
    text_concat_total = params[:'concat-total']
    text_concat_part = params[:'concat-part']


    #make new message
    @in_message = InMessage.new
    @in_message.msisdn = text_from_phone_no
    @in_message.message_type = text_type
    @in_message.message_text = text_body
    @in_message.to = text_to
    @in_message.network_code = text_network
    @in_message.message_id = text_message_id
    @in_message.concat = text_concat
    @in_message.concat_ref = text_concat_ref
    @in_message.concat_part = text_concat_part
    @in_message.concat_total = text_concat_total
    @in_message.message_timestamp = Time.now
    @in_message.status = "received"
    @in_message.posted_to_fb = false


    #save message do DB
    if @in_message.save
      logger.info("#{Time.now} Message from #{text_from_phone_no} received and saved!")
      #render :nothing => true # this will supply the needed http 200 OK
    else
      logger.error("#{Time.now} Received message could not be saved due to an error!")
      #render :nothing => true # this will supply the needed http 200 OK
    end


    #write a polite reply
    nexmo = Nexmo::Client.new(ENV["NEXMO_KEY"], ENV["NEXMO_SECRET"])


    if !text_from_phone_no.nil? and !text_body.nil?

      #if  text_from_phone_no[0..1] == '31'
      #  #  it's dutch!
      #  new_text_from_phone_no = text_from_phone_no[0..1] + '0' + text_from_phone_no[2..text_from_phone_no.length]
      #  text_from_phone_no = new_text_from_phone_no
      #end

      text_from_phone_no = '+' + text_from_phone_no
      response = nexmo.send_message({
                                        :from => ENV["NEXMO_FROM"],
                                        :to => text_from_phone_no,
                                        :text => t('in_messages.default_reply')
                                    })

      logger.info("#{Time.now} Sending text to #{text_from_phone_no} content: #{t('default_reply')}")


      if response.ok?
        logger.info("#{Time.now} Replied OK to #{text_from_phone_no} messageId #{text_message_id}")
        @in_message.status = "replied"
        @in_message.save
        render :nothing => true # this will supply the needed http 200 OK
      elsif response.failure?
        raise response.error
      end

    else
      logger.info("#{Time.now} Nothing to send!")
      render :nothing => true # this will supply the needed http 200 OK

    end

  end

end

app/helpers/in_messages_helper.rb
module InMessagesHelper
end

app/views/in_messages/_form.html.erb
<%= form_for @in_message, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :message_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :to, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :msisdn, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :msisdn, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :network_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :network_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :message_id, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_timestamp, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :message_timestamp, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :message_text, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :concat, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :concat, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :concat_ref, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :concat_ref, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :concat_total, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :concat_total, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :concat_part, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :concat_part, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :posted_to_fb, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :posted_to_fb, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                in_messages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/in_messages/edit.html.erb
<%- model_class = InMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/in_messages/index.html.erb
<%- model_class = InMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  <fieldset><strong><%= t('.messages_number') %><%= ENV["NEXMO_FROM"] %></strong></fieldset>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <!--<th><%= model_class.human_attribute_name(:message_type) %></th>-->
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:msisdn) %></th>
      <!--<th><%= model_class.human_attribute_name(:network_code) %></th>-->
      <!--<th><%= model_class.human_attribute_name(:message_id) %></th>-->
      <th><%= model_class.human_attribute_name(:message_timestamp) %></th>
      <th><%= model_class.human_attribute_name(:message_text) %></th>
      <!--<th><%= model_class.human_attribute_name(:concat) %></th>-->
      <!--<th><%= model_class.human_attribute_name(:concat_ref) %></th>-->
      <!--<th><%= model_class.human_attribute_name(:concat_total) %></th>-->
      <!--<th><%= model_class.human_attribute_name(:concat_part) %></th>-->
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:posted_to_fb) %></th>
      <!--<th><%= model_class.human_attribute_name(:created_at) %></th>-->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @in_messages.each do |in_message| %>
      <tr>
        <td><%= link_to in_message.id, in_message_path(in_message) %></td>
        <!--<td><%= in_message.message_type %></td>-->
        <td><%= in_message.to %></td>
        <td><%= in_message.msisdn %></td>
        <!--<td><%= in_message.network_code %></td>-->
        <!--<td><%= in_message.message_id %></td>-->
        <td><%= in_message.message_timestamp %></td>
        <td><%= in_message.message_text %></td>
        <!--<td><%= in_message.concat %></td>-->
        <!--<td><%= in_message.concat_ref %></td>-->
        <!--<td><%= in_message.concat_total %></td>-->
        <!--<td><%= in_message.concat_part %></td>-->
        <td><%= in_message.status %></td>
        <td><%= in_message.posted_to_fb %></td>
        <!--<td><%=l in_message.created_at %></td>-->
        <td>
          <%= link_to t('helpers.titles.show'), in_message_path(in_message), :class => 'btn btn-mini' %>
          <% if can? :manage, in_message && in_message.posted_to_fb != true %>
            <%= link_to t('Mark as Posted'),
                        mark_as_posted_in_message_path(in_message, :posted => true), :method => :put,
                 :class => 'btn btn-mini'%>
          <% end %>
          <% if can? :delete, in_message %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      in_message_path(in_message),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/in_messages/new.html.erb
<%- model_class = InMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/in_messages/show.html.erb
<%- model_class = InMessage -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:message_type) %>:</strong></dt>
    <dd><%= @in_message.message_type %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
    <dd><%= @in_message.to %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:msisdn) %>:</strong></dt>
    <dd><%= @in_message.msisdn %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:network_code) %>:</strong></dt>
    <dd><%= @in_message.network_code %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:message_id) %>:</strong></dt>
    <dd><%= @in_message.message_id %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:message_timestamp) %>:</strong></dt>
    <dd><%= @in_message.message_timestamp %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:message_text) %>:</strong></dt>
    <dd><%= @in_message.message_text %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:concat) %>:</strong></dt>
    <dd><%= @in_message.concat %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:concat_ref) %>:</strong></dt>
    <dd><%= @in_message.concat_ref %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:concat_total) %>:</strong></dt>
    <dd><%= @in_message.concat_total %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:concat_part) %>:</strong></dt>
    <dd><%= @in_message.concat_part %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
    <dd><%= @in_message.status %></dd>
  </div>
  <div class="row">
    <dt><strong><%= model_class.human_attribute_name(:posted_to_fb) %>:</strong></dt>
    <dd><%= @in_message.posted_to_fb %></dd>
  </div>
  </dl>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                in_messages_path, :class => 'btn' %>
    <% if can? :manage, @in_message %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_in_message_path(@in_message), :class => 'btn' %>
    <% end %>
    <% if can? :delete, @in_message %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  in_message_path(@in_message),
                  :method => 'delete',
                  :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                  :class => 'btn btn-danger' %>
    <% end %>
  </div>