config/routes.rb
Buurtsms::Application.routes.draw do

  resources :in_messages do
    collection do
      get :getmessage
    end
    member do
      put :mark_as_posted
    end
  end

  resources :out_messages

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'home#index'

end

app/models/out_message.rb
class OutMessage < ActiveRecord::Base
  STATUSES = %w"sent unsent"

  attr_accessible :direction, :error_text, :from, :in_messsage_id, :message_date, :message_id, :status, :text, :timestamp, :to, :type
end

app/controllers/out_messages_controller.rb
class OutMessagesController < ApplicationController
  before_filter :authenticate_user! #, :except => [:getmessage]
  load_and_authorize_resource #:except => [:getmessage]
  # GET /out_messages
  # GET /out_messages.json
  def index
    @out_messages = OutMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @out_messages }
    end
  end

  # GET /out_messages/1
  # GET /out_messages/1.json
  def show
    @out_message = OutMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @out_message }
    end
  end

  # GET /out_messages/new
  # GET /out_messages/new.json
  def new
    @out_message = OutMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @out_message }
    end
  end

  # GET /out_messages/1/edit
  def edit
    @out_message = OutMessage.find(params[:id])
  end

  # POST /out_messages
  # POST /out_messages.json
  def create
    @out_message = OutMessage.new(params[:out_message])

    respond_to do |format|
      if @out_message.save
        format.html { redirect_to @out_message, notice: 'Out message was successfully created.' }
        format.json { render json: @out_message, status: :created, location: @out_message }
      else
        format.html { render action: "new" }
        format.json { render json: @out_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /out_messages/1
  # PUT /out_messages/1.json
  def update
    @out_message = OutMessage.find(params[:id])

    respond_to do |format|
      if @out_message.update_attributes(params[:out_message])
        format.html { redirect_to @out_message, notice: 'Out message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @out_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /out_messages/1
  # DELETE /out_messages/1.json
  def destroy
    @out_message = OutMessage.find(params[:id])
    @out_message.destroy

    respond_to do |format|
      format.html { redirect_to out_messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/out_messages_helper.rb
module OutMessagesHelper
end

app/views/out_messages/_form.html.erb
<%= form_for @out_message, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :from, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :from, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :to, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :to, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :text, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :timestamp, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :timestamp, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :message_date, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :message_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :error_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :error_text, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :in_message_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :in_message_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                out_messages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/out_messages/edit.html.erb
<%- model_class = OutMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/out_messages/index.html.erb
<%- model_class = OutMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:from) %></th>
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:text) %></th>
      <th><%= model_class.human_attribute_name(:timestamp) %></th>
      <th><%= model_class.human_attribute_name(:message_date) %></th>
      <th><%= model_class.human_attribute_name(:message_id) %></th>
      <th><%= model_class.human_attribute_name(:error_text) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:in_message_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @out_messages.each do |out_message| %>
      <tr>
        <td><%= link_to out_message.id, out_message_path(out_message) %></td>
        <td><%= out_message.from %></td>
        <td><%= out_message.to %></td>
        <td><%= out_message.type %></td>
        <td><%= out_message.text %></td>
        <td><%= out_message.timestamp %></td>
        <td><%= out_message.message_date %></td>
        <td><%= out_message.message_id %></td>
        <td><%= out_message.error_text %></td>
        <td><%= out_message.status %></td>
        <td><%= out_message.in_message_id %></td>
        <td><%=l out_message.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_out_message_path(out_message), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      out_message_path(out_message),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_out_message_path,
            :class => 'btn btn-primary' %>

app/views/out_messages/new.html.erb
<%- model_class = OutMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/out_messages/show.html.erb
<%- model_class = OutMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @out_message.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:to) %>:</strong></dt>
  <dd><%= @out_message.to %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @out_message.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @out_message.text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:timestamp) %>:</strong></dt>
  <dd><%= @out_message.timestamp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message_date) %>:</strong></dt>
  <dd><%= @out_message.message_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message_id) %>:</strong></dt>
  <dd><%= @out_message.message_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:error_text) %>:</strong></dt>
  <dd><%= @out_message.error_text %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @out_message.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:in_message_id) %>:</strong></dt>
  <dd><%= @out_message.in_message_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              out_messages_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_out_message_path(@out_message), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              out_message_path(@out_message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>