config/routes.rb
Buurtsms::Application.routes.draw do

  resources :in_messages do
    collection do
      get :getmessage
    end
    member do
      put :mark_as_posted
    end
  end

  resources :out_messages

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuurtSMS</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= csrf_meta_tags %>

</head>
<body>
<div id="wrap">

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <!-- Be sure to leave the brand out there if you want it shown -->
        <a class="brand" href="#"><%= t('navbar.company_name') %></a>

        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
          <ul class="nav">
            <% if user_signed_in? %>
              <li><%= link_to t('navbar.in_messages'), in_messages_path %></li>
              <!--<li><%= link_to t('navbar.out_messages') , out_messages_path %></li>-->
            <% end %>
          </ul>

          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><span class="user-email"><%= t('navbar.logged_in_as') + " " + current_user.email %></span></li>
              <li><%= link_to t('navbar.edit_account'), "/users/edit" %></li>

              <!--<li><%= link_to t('navbar.profile'), "/profile" %></li>-->
              <li class="divider"></li>
              <li><%= link_to t('navbar.logout'), destroy_user_session_path, :method => :delete %></li>

            <% end %>
          </ul>
        </div>

      </div>
    </div>
  </div>


  <!-- Begin page content -->
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </div>

  <div id="push"></div>
</div>

<!-- /container -->

<div id="footer">
  <div class="container">
    <p class="muted credit">&copy; <%= Time.now().strftime("%Y") %> Code for Europe. </p>
  </div>
</div>

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>
<%= yield :scripts %>
</body>
</html>